### ISSUE TITLE
New way to import private keys into wallet

### ISSUE THREAD

**Issue by joric** [samr7/vanitygen#1]
I just spend a day writting standalone python script for importing/exporting keys (mostly based on bitcointools).
Probably it's the only alternative to showwallet patch so far (it works with the same private key format).
Specially for those who didn't manage to build showwallet, but knows how to set up python.
Options: --dumpwallet - dumps all keys in json format; --importprivkey=<key> - imports private key from vanitygen
URL: https://github.com/joric/pywallet

**Comment by sumiydad** [comment]
please explain how to export
