### ISSUE TITLE
Namecoin address prefix problems

### ISSUE THREAD

**Issue by dhouck** [samr7/vanitygen#11]
I've encountered two problems with namecoin address generation, both with the prefix matching. Both of these were found using the Windows binaries for version 0.20

First, it says that certain Namecoin address prefixes are impossible when they are possible. I have seen this with `NC`, as below, `N`, and anything I've tried beginning with `M`:

```
C:\Program Files\Vanitygen>vanitygen64.exe -iN NC
Prefix 'NC' not possible
Hint: valid namecoin addresses begin with "M" or "N"

C:\Program Files\Vanitygen>vanitygen64.exe -iN NCoin
Difficulty: 4553521
Pattern: NCoin
Address: NCoinrjdvgjWXR81W6B9CNxT6tLgpAfZaj
Privkey: 74cKBhX2UWzutTPcvBvMDZA1HhSuVQ4NdLtU5VwmW4WnriN2fGW
```

The second issue is only probably a bug a bug (p < 1 in a million), but the case-insensitive match doesn't seem case insensitive for namecoin addresses: out of 10 addresses of the format `NCoin` that I generated, all with the -i flag, exactly 0 of them had a different capitalization despite there being two characters where this is possible (the `C` and the `n`).

**Comment by samr7** [comment]
It would appear that the prefix case-enumerator was skipping the last possible combination.  In your 'NC' example, it was generating 'nc', 'Nc', and 'nC' but not 'NC'.  Nice find!

This should hopefully resolve both problems you've found.
https://github.com/samr7/vanitygen/commit/69a380c29ce4283ad6631888135347eb67adfe2e
