### ISSUE TITLE
Fatal errors in Ubuntu

### ISSUE THREAD

**Issue by cvengler** [samr7/vanitygen#118]
`cc -ggdb -O3 -Wall   -c -o vanitygen.o vanitygen.c
In file included from vanitygen.c:32:0:
pattern.h:54:12: error: field ‘vxc_bntarg’ has incomplete type
  BIGNUM    vxc_bntarg;
            ^~~~~~~~~~
pattern.h:55:12: error: field ‘vxc_bnbase’ has incomplete type
  BIGNUM    vxc_bnbase;
            ^~~~~~~~~~
pattern.h:56:12: error: field ‘vxc_bntmp’ has incomplete type
  BIGNUM    vxc_bntmp;
            ^~~~~~~~~
pattern.h:57:12: error: field ‘vxc_bntmp2’ has incomplete type
  BIGNUM    vxc_bntmp2;
            ^~~~~~~~~~
vanitygen.c: In function ‘vg_thread_loop’:
vanitygen.c:134:21: error: ‘BN_MASK2’ undeclared (first use in this function); did you mean ‘BN_BITS2’?
    if ((rekey_at == BN_MASK2) || (rekey_at > rekey_max))
                     ^~~~~~~~
                     BN_BITS2
vanitygen.c:134:21: note: each undeclared identifier is reported only once for each function it appears in
<eingebaut>: recipe for target 'vanitygen.o' failed
make: *** [vanitygen.o] Error 1`

This happens when I run make in ubuntu 18.04 LTS

**Comment by DesWurstes** [comment]
Duplicate: https://github.com/samr7/vanitygen/issues/116

**Comment by Wikinaut** [comment]
Duplicate #106 (see https://github.com/samr7/vanitygen/issues/106#issuecomment-342441203 for a solution)

**Comment by ilovelinux** [comment]
See https://github.com/samr7/vanitygen/issues/116#issuecomment-405227213 for a workaround/solution

**Comment by anemol** [comment]
Download an old version of OpenSSL
https://www.openssl.org/source/old/1.0.0/

For example the 1.0.0s: https://www.openssl.org/source/old/1.0.0/openssl-1.0.0s.tar.gz 
- Extract the tar.gz in a directory (/home/user/openssl-1.0.0s for example)
- Go in this directory and launch "make"

Then modify the makefile of Vanitygen
```
CFLAGS=-ggdb -O3 -Wall -I/home/user/openssl-1.0.0s/include -L/home/user/openssl-1.0.0s/
```
