### ISSUE TITLE
vanitygen.c:26:10: fatal error: 'openssl/sha.h' file not found

### ISSUE THREAD

**Issue by jacks0n9** [samr7/vanitygen#134]
When I cd into the vanitygen directory (mac) and type make, it gives me the error "vanitygen.c:26:10: fatal error: 'openssl/sha.h' file not found"

**Comment by EugenioMoro** [comment]
You need to install `libssl-dev`

**Comment by adityasuseno** [comment]
`sudo apt install libssl-dev`
