### ISSUE TITLE
pcre.h: No such file or directory

### ISSUE THREAD

**Issue by Lohoris** [samr7/vanitygen#18]
I have installed the packages `pcre` and `pcre++` with `port`, but it still complains it can't find `pcre.h`...

```
looris@Palace-of-the-Nine-Moons:~/ext-Sviluppo/vanitygen $ make
cc -ggdb -O3 -Wall   -c -o pattern.o pattern.c
pattern.c:32:18: error: pcre.h: No such file or directory
pattern.c:1604: error: expected specifier-qualifier-list before ‘pcre’
```

Using OSX 10.6

**Comment by ghost** [comment]
Missing h file typically means you don't have the dev package. So try installing libpcre++-dev

**Comment by Lohoris** [comment]
True, but there is no such package, and the normal pcre package likely already is a dev one:

```
pcre @8.12 (devel)
    Perl Compatible Regular Expressions Library

pcre++ @0.9.5 (devel)
    C++ wrapper for the Perl Compatible Regular Expressions Library

pcrexx @0.9.5 (devel)
    C++ wrapper for the Perl Compatible Regular Expressions Library
```

**Comment by ghost** [comment]
Oh, that's odd. I'm not on OSX. On Ubuntu there is dev packages. If the normal package doesn't contain h files then it can't be a dev version. Well, unless they get put somewhere non-standard and aren't found in the include path. So you might look into that. Any h files installed need to be in the "include" path to be found. Perhaps on OSX they need to be copied or moved.

**Comment by Lohoris** [comment]
Someone else had the same problem: http://bitcoin.stackexchange.com/questions/6004/osx-vanitygen-broken-makefile

Apparently it is fixed by linking `/opt/local/include/pcre.h` into `/usr/include/`.
