### ISSUE TITLE
Error compiling on Linux Mint

### ISSUE THREAD

**Issue by dstinebaugh** [samr7/vanitygen#74]
running into the following error when trying to "make"

```
$ make
cc -ggdb -O3 -Wall   -c -o vanitygen.o vanitygen.c
cc -ggdb -O3 -Wall   -c -o pattern.o pattern.c
pattern.c:32:18: fatal error: pcre.h: No such file or directory
 #include <pcre.h>
                  ^
compilation terminated.
make: *** [pattern.o] Error 1
```

**Comment by dstinebaugh** [comment]
n/m I'm an idiot, apt-get install libpcre-ocaml libpcre++-dev seems to have taken care of the dependencies and it compiled just fine. It's late, sorry.

**Comment by RainbowAsteroids** [comment]
Thanks, I'm an idiot too.

**Comment by DataCourier** [comment]
Same here, would be nice to update the installation instructions.
