### ISSUE TITLE
Getting error when compiling on xubuntu

### ISSUE THREAD

**Issue by micycle8778** [samr7/vanitygen#94]
Whenever I use the command `make`, it returns this blob of text:

    cc -ggdb -O3 -Wall   -c -o vanitygen.o vanitygen.c
    make: cc: Command not found
    <builtin>: recipe for target 'vanitygen.o' failed
    make: *** [vanitygen.o] Error 127

**Comment by just-an-dev** [comment]
Try install gcc 😃

**Comment by micycle8778** [comment]
Thanks!
